eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
      
spring:
  datasource:
     #mysql数据库配置
     #url: jdbc:mysql://localhost:3306/shopweb?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
     #username: root
     #password: 123456
     #oracle
     driverClassName: oracle.jdbc.driver.OracleDriver
     url: jdbc:oracle:thin:@47.97.98.41:1521:orcl
     username: hlwdq
     password: Hds130818ncbxjs
     initialSize: 2
     minIdle: 1
     maxActive: 50
     maxWait: 60000
     timeBetweenEvictionRunsMillis: 60000
     minEvictableIdleTimeMillis: 300000
     validationQuery: select 'x'
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     poolPreparedStatements: true
     maxPoolPreparedStatementPreConnectionSize: 20
     maxOpenPreparedStatements: 20
     filters: config,wall,stat
     connectionProperties: druid.stat.slowSqlMillis=200;druid.stat.logSlowSql=true;config.decrypt=true