eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
      
#配置mybatis
mybatis:
  mapperLocations: classpath:mapper/*.xml

server:
  port: 9000
      
spring:
  profiles:
    active: me
  application:
    name: sign-gateway-zuul

zuul:
  strip-prefix: true                   #去掉URL前缀，比如访问的是/sign-user/user/info,则zuul在转发时会去掉/sign-user
  routes:
    api-user:                          #面向服务的路由配置,此名称可以自定义
      path: /sign-user/**
      serviceId: sign-user
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000      
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: auth/register

header:
  username: CUR_USERNAME