server:
  port: 8081
spring:
  application:
    name: sign-eurka
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: false
    fetch-registry: false